<?php
/**
 * @file
 * Code for the GSB Feature Admission Event Content Type feature.
 */

include_once 'gsb_feature_admission_event_ct.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function gsb_feature_admission_event_ct_form_admission_event_node_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id != 'admission_event_node_form') {
    return;
  }

  $language = $form['language']['#value'];
  $form['field_event_speakers']['#after_build'] = array('gsb_feature_admission_event_ct_after_build');

  $form['field_link_single']['#states'] = array(
    'invisible' => array(
      ':input[name="field_event_detail[' . $language . ']"],value="1"' => array('!value' => (string)'1'),
      ':input[name="field_event_detail[' . $language . ']"],value=""' => array('!value' => (string)''),
    ),
    'required' => array(
      ':input[name="field_event_detail[' . $language . ']"]' => array('value' => (string)'1'),
    ),
  );

  $form['field_body']['#states']['required'][':input[name="field_event_detail[' . $language . ']"]'] = array(
    array('value' => (string)'0'),
  );

  $form['field_event_location'][$language][0]['field_link_map']['#states']['invisible'][':input[name="field_event_detail[' . $language . ']"]'] = array(
    array('value' => (string)'1'),
  );

  drupal_add_js(drupal_get_path('module', 'gsb_feature_admission_event_ct') . '/js/gsb_feature_admission_event_ct.js');

  // Perform additional validation.
  $form['#validate'][] = 'gsb_feature_admission_event_ct_form_validate';
}


/**
 * gsb_feature_admission_event_ct_after_build().
 */
function gsb_feature_admission_event_ct_after_build($form, &$form_state) {
  $language = $form['#language'];
  foreach ($form[$language] as $key => $value) {
    if (is_numeric($key) && $key >= 0) {
      // Change to apply #states for Speakers to show hide fields
      $form[$language][$key]['field_first_name']['#states']['invisible'] = array(
        ':input[name="field_event_speakers[' . $language . '][' . $key . '][field_speakers_person_type][' . $language . ']"]' => array(
          array('value' => '0'),
        ),
      );

      $form[$language][$key]['field_last_name']['#states']['invisible'] = array(
        ':input[name="field_event_speakers[' . $language . '][' . $key . '][field_speakers_person_type][' . $language . ']"]' => array(
          array('value' => '0'),
        ),
      );

      $form[$language][$key]['field_link_single']['#states']['invisible'] = array(
        ':input[name="field_event_speakers[' . $language . '][' . $key . '][field_speakers_person_type][' . $language . ']"]' => array(
          array('value' => '0'),
        ),
      );

      $form[$language][$key]['field_person_ref']['#states']['invisible'] = array(
        ':input[name="field_event_speakers[' . $language . '][' . $key . '][field_speakers_person_type][' . $language . ']"]' => array(
          array('value' => '1'),
        ),
      );
    }
  }

  return $form;
}

/**
 * Validate callback
 *  - Conditionally validate field.
 */
function gsb_feature_admission_event_ct_form_validate($form, &$form_state) {
  $language = $form['language']['#value'];
  $values = $form_state['values'];
  // Validate the conditional mandatory fields.
  if ($values['field_event_detail'][$language][0]['value'] == '1') {
    if (empty($values['field_link_single'][$language][0]['value'])) {
      $field_label = $form['field_link_single'][$language]['#title'];
      form_set_error('field_link_single]['.$language.'][0][url', $field_label . ' field is required.');
    }
  }
  if ($values['field_event_detail'][$language][0]['value'] == '0') {
    if (empty($values['field_body'][$language][0]['value'])) {
      $field_label = $form['field_body'][$language]['#title'];
      form_set_error('field_body]['.$language.'][0][value', $field_label . ' field is required.');
    }
  }
}
